name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: windows-latest
      permissions:
        id-token: write
        contents: write
      steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          install-only: true
      -
        name: UPX version
        run: upx --version
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2.2.0
        with:
          version: 12.2.0 
          platform: x64
      - name: Run Build
        run: |
          cmd.exe /c "build.bat"
      - uses: actions/upload-artifact@v4
        with:
          name: DiscordFixer.exe
          path: DiscordFixer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: Beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "D:/a/DiscordFixer/DiscordFixer/DiscordFixer.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: Beta
          name: DiscordFixer
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: true
          prerelease: false
